### ISSUE TITLE
custom separator

### ISSUE THREAD

**Issue by GhisF** [shshemi/tabiew#1]
Nice little tool :) 
Do you consider to add an option to specify the separator to use ( tab,  ";",  "|" ... )  ?

Thanks

**Comment by shshemi** [comment]
Thank you,
Would you kindly elaborate more?
In which view (table view or detailed view)?
If in the table view, separators between rows or columns?

Thank you

**Comment by GhisF** [comment]
Hi,
I mean able to specify a custom separator for the input file, to be able to read a tab, comma or semi-column separated file (tsv, cvs...).  I mostly use tab separated ones.
Polars is able to manage such option, so it shouldn't be a big challenge to add this option.

Thanks :)

**Comment by shshemi** [comment]
Now I see.
The option has now been added to the main branch and will be released in the next version alongside other features.

Thank you for your suggestion.
