### ISSUE TITLE
ARM Build for Raspberry Pi

### ISSUE THREAD

**Issue by Write** [shshemi/tabiew#10]
Hello, lovely project.

Would it be possible to have an ARM pre-built binaries available ?

Thanks a lot.

**Comment by shshemi** [comment]
Hi, Thank you

Sure, I added compilation for Linux ARM v6 and v7 to the backlog.

If you are interested, compiling Tabiew is straightforward. Just install the latest version of Rust from [here](https://www.rust-lang.org/tools/install), and follow the [instructions in the README](https://github.com/shshemi/tabiew?tab=readme-ov-file#build-from-source).

Please be aware that it may take a while to compile.

**Comment by shshemi** [comment]
The ARM v7 and v8 pre-builds are included in the 0.6.2 release version.
