### ISSUE TITLE
stdin as file

### ISSUE THREAD

**Issue by iloveitaly** [shshemi/tabiew#13]
Looks like `-` is not supported as a alias for consuming stdin. This would be a great feature!

**Comment by shshemi** [comment]
Hey,
Thanks for the suggestion. I added it to the backlog. Unfortunately, I do not think it is going to be a possibility any time soon as some parser libraries used in Tabiew are only capable of reading from files.

**Comment by iloveitaly** [comment]
Ah, makes sense! Thanks for explaining.

**Comment by shshemi** [comment]
Reading from stdin is implemented and will be available in the next release. If you want to try it before release, kindly build the `main` branch from the source. Then use:
```sh
curl -sSL "https://raw.githubusercontent.com/shshemi/tabiew/refs/heads/main/tutorial/company.csv" | tw
```

**Comment by shshemi** [comment]
The latest released version should resolve your problem
