### ISSUE TITLE
Quick Search / Fuzzy Finder

### ISSUE THREAD

**Issue by hnorkowski** [shshemi/tabiew#17]
I like the tool very much. The only downside for me is that there is no convenient way to quickly search. I know you can search using SQL syntax which is very nice if you have complex conditions. However if you are just looking for a specific number or string its much overhead and not everyone is fluent is SQL. 

As there are already Vim-like keybinds it would be nice to have a vim-like search with '/' and maybe also add a fuzzy finder with a additional command.

What do you think of this idea?

**Comment by shshemi** [comment]
Searching with `/` has been in the backlog since the first version. However, it has raised a couple of questions in my brain. The most important one is the indexing method. Another solution is to generate the SQL instead of using an index.

**Comment by shshemi** [comment]
The fuzzy search ability is now available in the version `0.8.0`.

**Comment by hnorkowski** [comment]
Very nice, thanks for your effort!
