### ISSUE TITLE
MacOS installation

### ISSUE THREAD

**Issue by bhean** [shshemi/tabiew#5]
Hi,

Tabiew looks amazing... are you planing to make it available from _Homebrew_ (for example) for MacOS users as well?
I think that would be great...

Thanks,

**Comment by shshemi** [comment]
Hi,

Thank you kindly for your kind words.
I plan to publish Tabiew on multiple channels, such as Homebrew and PyPi. However, this would take some time to be ready and tested. Meanwhile, I suggest you install Tabiew using `cargo` on MacOS. Let me know if you need any assistance with the installation.

**Comment by shshemi** [comment]
I am glad to mention that Tabiew is now available to install on MacOS using Homebrew:
```bash
brew tap shshemi/homebrew-tabiew
brew install tabiew
```
Please try it out and let me know if anything is missing.

**Comment by bhean** [comment]
This is great, the installation works perfectly with Homebrew... thanks for your ultra-quick response 👍🏽

**Comment by sujitawake** [comment]
@shshemi, Would you consider providing standalone compiled binaries for Mac OS (both Intel and Silicon) builds?

I am aware that I can go the `brew` way, but there are certain times when it fails to impress due to various reasons.

**Comment by shshemi** [comment]
As of version 0.4.3, the compiled binary for Apple silicon is available on the download page. For Intel, however, one of the dependencies failed to compile, which needs further investigation.

**Comment by failable** [comment]
The brew installation still builds from the source like `cargo install tabiew`, which is super slow (> 20 minutes) when compiling `polars`.

**Comment by shshemi** [comment]
You can use the prebuilt binary from [here](https://github.com/shshemi/tabiew/releases/tag/v0.6.1).
Furthermore,I am planning to modify the Homebrew Formula to install from precompile binaries by default.

**Comment by gromgit** [comment]
`tabiew` is now available from Homebrew core with pre-built binaries. Just `brew update`. then `brew install tabiew`. No muss, no fuss. 😁

**Comment by bhean** [comment]
Great! Now the installation is as fast as expected, thanks!
